version: '2'
services:
  mysql:
    image: mysql:9.2
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "3306:3306"
    volumes:
      - .local/mysql5.7:/var/lib/mysql
    networks:
      - vr-match
networks:
  vr-match:
    external: true
