apiVersion: apps/v1
kind: Deployment
metadata:
  name: vr-match-${_ENVIRONMENT}
spec:
  replicas: ${_REPLICAS}
  selector:
    matchLabels:
      app: vr-match-${_ENVIRONMENT}
  template:
    metadata:
      labels:
        app: vr-match-${_ENVIRONMENT}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - vr-match-${_ENVIRONMENT}
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: vr-match-${_ENVIRONMENT}
        image: gcr.io/${PROJECT_ID}/vr-match-${_ENVIRONMENT}:${REVISION_ID}
        ports:
        - containerPort: 3000
        env:
          - name: API_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: vr-match-${_ENVIRONMENT}-secrets
                key: VR_MATCH_API_ENDPOINT
          - name: FIREBASE_API_KEY
            valueFrom:
              secretKeyRef:
                name: vr-match-${_ENVIRONMENT}-secrets
                key: FIREBASE_API_KEY
          - name: FIREBASE_AUTH_DOMAIN
            valueFrom:
              secretKeyRef:
                name: vr-match-${_ENVIRONMENT}-secrets
                key: FIREBASE_AUTH_DOMAIN
          - name: FIREBASE_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: vr-match-${_ENVIRONMENT}-secrets
                key: FIREBASE_DATABASE_URL
          - name: FIREBASE_PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: vr-match-${_ENVIRONMENT}-secrets
                key: FIREBASE_PROJECT_ID
          - name: FIREBASE_STORAGE_BUCKET
            valueFrom:
              secretKeyRef:
                name: vr-match-${_ENVIRONMENT}-secrets
                key: FIREBASE_STORAGE_BUCKET
          - name: FIREBASE_MESSAGING_SENDER_ID
            valueFrom:
              secretKeyRef:
                name: vr-match-${_ENVIRONMENT}-secrets
                key: FIREBASE_MESSAGING_SENDER_ID
          - name: FIREBASE_APP_ID
            valueFrom:
              secretKeyRef:
                name: vr-match-${_ENVIRONMENT}-secrets
                key: FIREBASE_APP_ID
          - name: GOOGLE_ANALYTICS_TRACKING_ID
            valueFrom:
              secretKeyRef:
                name: vr-match-${_ENVIRONMENT}-secrets
                key: GOOGLE_ANALYTICS_TRACKING_ID
