apiVersion: v1
kind: Service
metadata:
  name: vr-match-${_ENVIRONMENT}
spec:
  selector:
    app: vr-match-${_ENVIRONMENT}
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
