apiVersion: v1
kind: Service
metadata:
  name: vr-match-back-end-${_ENVIRONMENT}
spec:
  selector:
    app: vr-match-back-end-${_ENVIRONMENT}
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
