
-- MySQL Script generated by MySQL Workbench
-- Mon Jun  3 00:25:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vr_match
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vr_match` ;

-- -----------------------------------------------------
-- Schema vr_match
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vr_match` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `vr_match` ;

-- -----------------------------------------------------
-- Table `vr_match`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vr_match`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `firebase_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(190) NOT NULL,
  `introduction` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `firebase_id_UNIQUE` (`firebase_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vr_match`.`platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vr_match`.`platform` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(190) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `vr_match`.`user_platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vr_match`.`user_platform` (
  `user_id` BIGINT(20) NOT NULL,
  `platform_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`user_id`, `platform_id`),
  UNIQUE INDEX `UNIQUE` (`platform_id` ASC, `user_id` ASC),
  CONSTRAINT `user_platform_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `vr_match`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_platform_platform_id`
    FOREIGN KEY (`platform_id`)
    REFERENCES `vr_match`.`platform` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `vr_match`.`user_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vr_match`.`user_token` (
  `user_id` BIGINT(20) NOT NULL,
  `hash` VARCHAR(255) NOT NULL,
  `expiration_date` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  UNIQUE INDEX `token_UNIQUE` (`hash` ASC),
  PRIMARY KEY (`hash`),
  CONSTRAINT `user_token_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `vr_match`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `vr_match`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vr_match`.`image` (
  `id` BIGINT(20) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `image_type` INT NOT NULL,
  `placeholder_color` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `vr_match`.`user_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vr_match`.`user_image` (
  `user_id` BIGINT(20) NOT NULL,
  `image_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`user_id`, `image_id`),
  UNIQUE INDEX `UNIQUE` (`user_id` ASC, `image_id` ASC),
  CONSTRAINT `user_image_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `vr_match`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_image_image_id`
    FOREIGN KEY (`image_id`)
    REFERENCES `vr_match`.`image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `vr_match`.`user_favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vr_match`.`user_favorite` (
  `from_id` BIGINT(20) NOT NULL,
  `to_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`from_id`, `to_id`),
  UNIQUE INDEX `UNIQUE` (`from_id` ASC, `to_id` ASC),
  CONSTRAINT `user_favorite_from_id`
    FOREIGN KEY (`from_id`)
    REFERENCES `vr_match`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_favorite_to_id`
    FOREIGN KEY (`to_id`)
    REFERENCES `vr_match`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `vr_match`.`user_match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vr_match`.`user_match` (
  `from_id` BIGINT(20) NOT NULL,
  `to_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`from_id`, `to_id`),
  UNIQUE INDEX `UNIQUE` (`from_id` ASC, `to_id` ASC),
  CONSTRAINT `user_match_from_id`
    FOREIGN KEY (`from_id`)
    REFERENCES `vr_match`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_match_to_id`
    FOREIGN KEY (`to_id`)
    REFERENCES `vr_match`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `vr_match`.`user_skip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vr_match`.`user_skip` (
  `from_id` BIGINT(20) NOT NULL,
  `to_id` BIGINT(20) NOT NULL,
  `user_skipcol` VARCHAR(45) NULL,
  PRIMARY KEY (`from_id`, `to_id`),
  UNIQUE INDEX `UNIQUE` (`from_id` ASC, `to_id` ASC),
  CONSTRAINT `user_skip_from_id`
    FOREIGN KEY (`from_id`)
    REFERENCES `vr_match`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_skip_to_id`
    FOREIGN KEY (`to_id`)
    REFERENCES `vr_match`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
